import { Card, CardContent } from "@/components/ui/card"

// Define types for our glossary data
type GlossaryTerm = {
    term: string
    definition: string
    type?: "positive" | "neutral" | "negative"
}

export default function Glossary() {
    // Glossary terms data
    const glossaryTerms: GlossaryTerm[] = [
        {
            term: "Outperform",
            definition:
                'A stock rated as "Outperform" is expected to perform better than the overall market or a specific benchmark over the near-to-medium term. This rating suggests that the stock is likely to deliver higher returns compared to the average returns of other stocks in the same sector or market index. Investors might consider this stock a good buying opportunity.',
            type: "positive",
        },
        {
            term: "Neutral",
            definition:
                'A stock rated as "Neutral" is expected to perform in line with the overall market or a specific benchmark. This rating indicates that the stock is neither particularly attractive nor unattractive for investment. Investors may consider holding onto the stock, as it is not expected to either significantly outperform or underperform the market.',
            type: "neutral",
        },
        {
            term: "Underperform",
            definition:
                'A stock rated as "Underperform" is expected to perform worse than the overall market or a specific benchmark over the near-to-medium term. This rating suggests that the stock may deliver lower returns compared to the average returns of other stocks in the same sector or market index. Investors might consider selling the stock or avoiding it as an investment.',
            type: "negative",
        },
    ]

    // Disclaimer text
    const disclaimer = `This AI Analyst Stock Report is automatically generated by our AI systems using advanced algorithms and publicly available financial, technical, and market data. While the information provided aims to be accurate and insightful, it is intended for informational purposes only and should not be considered financial advice. Any content created by an AI (Artificial Intelligence) system may contain inaccuracies and/or errors. Investing in stocks carries inherent risks, and past performance is not indicative of future results. This report does not account for your personal financial circumstances, objectives, or risk tolerance. Always conduct your own research or consult with a qualified financial advisor before making investment decisions. The analysis and recommendations provided are based on historical and current data and may not fully reflect future market conditions or unexpected developments. Neither the creators of this report nor its affiliated entities guarantee the accuracy, completeness, or reliability of the information presented. Use this report at your own discretion and risk.`

    // Function to get term color based on type
    const getTermColor = (type?: string) => {
        switch (type) {
            case "positive":
                return "text-teal-500"
            case "negative":
                return "text-rose-500"
            default:
                return "text-gray-700"
        }
    }

    return (
        <div className="container mx-auto">
            <h1 className="text-3xl font-bold mb-6">Glossary</h1>

            <div className="shadow-[0px_0px_10px_1px_#0000001A]">
                <Card className="mb-8">
                    <CardContent className="pt-6">
                        <div className="space-y-8">
                            {glossaryTerms.map((item, index) => (
                                <div key={index} className={index < glossaryTerms.length - 1 ? "pb-6 border-b" : ""}>
                                    <h2 className={`text-xl font-semibold mb-3 ${getTermColor(item.type)}`}>{item.term}</h2>
                                    <p className="text-gray-700">{item.definition}</p>
                                </div>
                            ))}
                        </div>
                    </CardContent>
                </Card>

                <Card>
                    <CardContent className="pt-6">
                        <h2 className="text-xl font-semibold mb-3">Disclaimer</h2>
                        <p className="text-sm text-gray-600">{disclaimer}</p>
                    </CardContent>
                </Card>
            </div>
        </div>
    )
}
